# Generated by Django 5.2.4 on 2025-07-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Commodity name (e.g., Gold, Oil, Silver)', max_length=100, unique=True)),
                ('symbol', models.CharField(help_text='Commodity symbol (e.g., XAU, WTI, XAG)', max_length=10)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., oz, barrel, lb)', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current commodity price', max_digits=12)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price change from previous close', max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, help_text='Percentage change', max_digits=6)),
                ('exchange', models.CharField(blank=True, help_text='Primary exchange', max_length=50)),
                ('high_52_week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_52_week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cryptocurrency name (e.g., Bitcoin, Ethereum)', max_length=100)),
                ('symbol', models.CharField(help_text='Crypto symbol (e.g., BTC, ETH)', max_length=10, unique=True)),
                ('current_price', models.DecimalField(decimal_places=8, help_text='Current crypto price in USD', max_digits=15)),
                ('price_change', models.DecimalField(decimal_places=8, help_text='Price change from previous close', max_digits=15)),
                ('percentage_change', models.DecimalField(decimal_places=2, help_text='Percentage change', max_digits=6)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization in USD', null=True)),
                ('volume_24h', models.BigIntegerField(default=0, help_text='24-hour trading volume')),
                ('circulating_supply', models.BigIntegerField(blank=True, help_text='Circulating supply', null=True)),
                ('total_supply', models.BigIntegerField(blank=True, help_text='Total supply', null=True)),
                ('ath', models.DecimalField(blank=True, decimal_places=8, help_text='All-time high', max_digits=15, null=True)),
                ('atl', models.DecimalField(blank=True, decimal_places=8, help_text='All-time low', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['-market_cap'],
            },
        ),
        migrations.CreateModel(
            name='MarketTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock symbol (e.g., AAPL, TSLA)', max_length=10, unique=True)),
                ('company_name', models.CharField(help_text='Full company name', max_length=200)),
                ('exchange', models.CharField(help_text='Stock exchange (e.g., NYSE, NASDAQ)', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current stock price', max_digits=12)),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Price change from previous close', max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, help_text='Percentage change', max_digits=6)),
                ('volume', models.BigIntegerField(default=0, help_text='Trading volume')),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalization', null=True)),
                ('high_52_week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_52_week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Ticker',
                'verbose_name_plural': 'Market Tickers',
                'ordering': ['symbol'],
            },
        ),
    ]
