# Generated by Django 5.2.4 on 2025-07-10 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_commodity_cryptocurrency_marketticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsprovider',
            name='country',
            field=models.ForeignKey(default=1, help_text='Country where this provider is based', on_delete=django.db.models.deletion.CASCADE, related_name='news_providers', to='news.country'),
        ),
    ]
