# Generated by Django 5.2.4 on 2025-07-10 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsprovider_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title or headline', max_length=255)),
                ('content', models.TextField(help_text='Post content or description')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('other', 'Other')], default='other', help_text='Social media platform', max_length=20)),
                ('author_name', models.CharField(help_text='Author or account name', max_length=100)),
                ('author_handle', models.CharField(blank=True, help_text='Social media handle (e.g., @username)', max_length=100)),
                ('post_url', models.URLField(blank=True, help_text='Direct link to the original post')),
                ('image_url', models.URLField(blank=True, help_text='URL to post image or media')),
                ('likes', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('shares', models.PositiveIntegerField(default=0, help_text='Number of shares')),
                ('comments', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this post prominently')),
                ('is_active', models.BooleanField(default=True, help_text='Display this post on the site')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the post was originally published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AlterField(
            model_name='newsprovider',
            name='country',
            field=models.ForeignKey(help_text='Country where this provider is based', on_delete=django.db.models.deletion.CASCADE, related_name='news_providers', to='news.country'),
        ),
    ]
