# Generated by Django 5.2.4 on 2025-07-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_socialmediapost_alter_newsprovider_country'),
    ]

    operations = [
    ]
