# Generated by Django 5.1.6 on 2025-07-11 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_newsarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketticker',
            name='currency',
            field=models.CharField(choices=[('AED', 'United Arab Emirates Dirham'), ('AUD', 'Australian Dollar'), ('BRL', 'Brazilian Real'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CLP', 'Chilean Peso'), ('CNY', 'Chinese Yuan'), ('CZK', 'Czech Koruna'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('IDR', 'Indonesian Rupiah'), ('ILS', 'Israeli New Shekel'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso'), ('MYR', 'Malaysian Ringgit'), ('NOK', 'Norwegian Krone'), ('NZD', 'New Zealand Dollar'), ('PHP', 'Philippine Peso'), ('PKR', 'Pakistani Rupee'), ('PLN', 'Polish Zloty'), ('RUB', 'Russian Ruble'), ('SAR', 'Saudi Riyal'), ('SEK', 'Swedish Krona'), ('SGD', 'Singapore Dollar'), ('THB', 'Thai Baht'), ('TRY', 'Turkish Lira'), ('USD', 'US Dollar'), ('VND', 'Vietnamese Dong'), ('ZAR', 'South African Rand'), ('ZIG', 'Zimbabwean Dollar')], default='USD', help_text='Currency the stock is traded in', max_length=3),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Current stock price', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='high_52_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='low_52_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='market_cap',
            field=models.BigIntegerField(blank=True, help_text='Market capitalization', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='volume',
            field=models.BigIntegerField(default=0, help_text='Trading volume', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='marketticker',
            index=models.Index(fields=['symbol'], name='news_market_symbol_f5c3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='marketticker',
            index=models.Index(fields=['exchange'], name='news_market_exchang_cb4a30_idx'),
        ),
        migrations.AddIndex(
            model_name='marketticker',
            index=models.Index(fields=['currency'], name='news_market_currenc_716610_idx'),
        ),
        migrations.AddIndex(
            model_name='marketticker',
            index=models.Index(fields=['is_active'], name='news_market_is_acti_0d6b1c_idx'),
        ),
    ]
