# Generated by Django 5.1.6 on 2025-07-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_marketticker_currency_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketticker',
            name='news_market_symbol_f5c3f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketticker',
            name='news_market_exchang_cb4a30_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketticker',
            name='news_market_currenc_716610_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketticker',
            name='news_market_is_acti_0d6b1c_idx',
        ),
        migrations.RemoveField(
            model_name='marketticker',
            name='currency',
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Current stock price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='high_52_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='low_52_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='market_cap',
            field=models.BigIntegerField(blank=True, help_text='Market capitalization', null=True),
        ),
        migrations.AlterField(
            model_name='marketticker',
            name='volume',
            field=models.BigIntegerField(default=0, help_text='Trading volume'),
        ),
    ]
