# Generated by Django 5.1.6 on 2025-07-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_marketticker_currency_alter_marketticker_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketticker',
            name='details_link',
            field=models.URLField(blank=True, help_text='URL to view more details about this ticker', max_length=500, null=True),
        ),
    ]
