# Generated by Django 5.1.6 on 2025-07-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_marketticker_details_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text='Base currency code (e.g., USD, EUR)', max_length=3)),
                ('quote_currency', models.CharField(help_text='Quote currency code (e.g., USD, EUR)', max_length=3)),
                ('currency_pair', models.CharField(help_text='Currency pair (e.g., EUR/USD, GBP/USD)', max_length=10, unique=True)),
                ('description', models.CharField(help_text='Description of the currency pair (e.g., Euro to Dollar)', max_length=100)),
                ('market', models.CharField(choices=[('forex', 'FOREX'), ('crypto', 'Crypto'), ('stocks', 'Stocks'), ('commodities', 'Commodities')], default='forex', help_text='Market type', max_length=20)),
                ('current_rate', models.DecimalField(decimal_places=6, help_text='Current exchange rate', max_digits=12)),
                ('rate_change', models.DecimalField(decimal_places=6, help_text='Rate change from previous close', max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, help_text='Percentage change from previous close', max_digits=6)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=6, help_text='24-hour high rate', max_digits=12, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=6, help_text='24-hour low rate', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the exchange rate is currently active')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of last data update')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of record creation')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency_pair'],
                'indexes': [models.Index(fields=['currency_pair'], name='news_exchan_currenc_aa346e_idx'), models.Index(fields=['market'], name='news_exchan_market_c267c0_idx')],
            },
        ),
    ]
